In [1]:
import pandas as pd
import numpy as np

In [2]:
year1996 = pd.read_csv("C:/Users/hp/CSA_AGRI_DATA/2003 - 2004/Field Information - 1996.csv")

C:\Users\hp\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (7,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
year1996.head()

,reg,zone,dist,fa,ea,hh,pweight,hhsize,pratio,hid,...,alocarea,anotmeas,enumarea,comparea,areah,area,plunit,plocal,prodq,prod
0,1,1,2,5,3,1,170.31,2,0.044858,1,...,.25,5,325.55,325.55,.032555,325.55,,,,
1,1,1,2,5,3,1,170.31,2,0.044858,1,...,.5,5,671.4,656.52,.06714,671.4,10,,7.9225,79.225
2,1,1,2,5,3,1,170.31,2,0.044858,1,...,2.25,5,6693.68,6693.69,.669368,6693.68,30,,106.4295,1064.295
3,1,1,2,5,3,1,170.31,2,0.044858,1,...,1,5,2067.64,2067.64,.206764,2067.64,30,,17.3682,173.682
4,1,1,2,5,3,1,170.31,2,0.044858,1,...,2.5,5,6869.62,6869.62,.686962,6869.62,40,,87.2442,872.442

In [10]:
def writing(csa_agri_data_version1, writer):
    csa_agri_data_version1.to_excel(writer)

In [19]:
def featureselection2(csa_year):
    columns = ['reg', 'zone', 'fweight', 'crop', 'irrg', 'trees', 'seedtype', 'damage', 'dreason', 'dpercent', 'dmeasure', 'dmtype', 'dmchem', 'fert', 'ferttype', 'chemtype', 'natutyp', 'apercent', 'enumarea', 'comparea', 'area', 'prodq', 'prod']
    column = ['REG', 'ZONE', 'FWEIGHT', 'CROP', 'IRRG', 'TREES', 'SEEDTYPE', 'DAMAGE', 'DREASON', 'DPERCENT', 'DMEASURE', 'DMTYPE', 'DMCHEM', 'FERT', 'FERTTYPE', 'D22A', 'D23', 'APERCENT', 'ENUMAREA', 'COMPAREA', 'AREA', 'PRODQ', 'PROD']
    csa_agri_data_version1 = pd.ExcelWriter('C:/Users/hp/CSA_AGRI_DATA/csa_data_version1/field_info1_1996.xlsx')
    #csa_agri_data_version1.to_excel(csa_agri_data_version1)
    for col in columns:
        for cols in column:
            csa_agri_data_version1[cols] = csa_year[col]
    return csa_agri_data_version1

In [20]:
featureselection2(year1996)

TypeError: '_XlsxWriter' object does not support item assignment

In [ ]:
writer = pd.ExcelWriter('C:/Users/hp/CSA_AGRI_DATA/csa_data_version1/field_info1_1996.csv')
writing(writer)