In [3]:
import numpy as np
import pandas as pd

In [4]:
BarAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/BarleyAreaProFet.csv')
MazAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/MaizeAreaProFet.csv')
MilAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/MilletAreaProFet.csv')
SorgAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/SorghumAreaProFet.csv')
TefAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/TeffAreaProFet.csv')
WhetAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/WheatAreaProFet.csv')
ChPRAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/Red_Chick_peasAreaProFet.csv')
WhHBAreaPro = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/area_product/fet_areapro/White_haricot_beansAreaProFet.csv')
##################################################################################################################
BarCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/BarTig.csv')
MazCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/MazTig.csv')
MilCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/MilTig.csv')
SorgCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/SorgTig.csv')
TefCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/TefTig.csv')
WhetCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/WhetTig.csv')
ChPRCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/ChPRTig.csv')
WhHBCsa = pd.read_csv('C:/Users/hp/CSA_AGRI_DATA/csa_data_version2/fet_crop/WhHBTig.csv')
###################################################################################################################
MetroData = pd.read_csv('C:/Users/hp/METRO_DATA/Fet_Metro.csv')

In [5]:
BarAreaPro.head()

   Unnamed: 0  Zone  Year     Area  Production  Yield
0           0     1  1996    383.0     1754.00   4.58
1           1     2  1996  18729.0   173601.00   9.27
2           2     3  1996  19847.0   251979.00  12.70
3           3     4  1996    588.0    24166.85  22.00
4           4     1  1997    500.0     1863.00   3.73

In [6]:
BarAreaPro = BarAreaPro.drop([0,1,2,3,48,49,50,51])
MazAreaPro = MazAreaPro.drop([0,1,2,3,48,49,50,51])
MilAreaPro = MilAreaPro.drop([0,1,2,3,48,49,50,51])
SorgAreaPro = SorgAreaPro.drop([0,1,2,3,48,49,50,51])
TefAreaPro = TefAreaPro.drop([0,1,2,3,48,49,50,51])
WhetAreaPro = WhetAreaPro.drop([0,1,2,3,48,49,50,51])
ChPRAreaPro = ChPRAreaPro.drop([0,1,2,3,48,49,50,51])
WhHBAreaPro = WhHBAreaPro.drop([0,1,2,3,48,49,50,51])

In [7]:
BarAreaPro = BarAreaPro.reset_index().drop(columns = ['index'])
MazAreaPro = MazAreaPro.reset_index().drop(columns = ['index'])
MilAreaPro = MilAreaPro.reset_index().drop(columns = ['index'])
SorgAreaPro = SorgAreaPro.reset_index().drop(columns = ['index'])
TefAreaPro = TefAreaPro.reset_index().drop(columns = ['index'])
WhetAreaPro = WhetAreaPro.reset_index().drop(columns = ['index'])
ChPRAreaPro = ChPRAreaPro.reset_index().drop(columns = ['index'])
WhHBAreaPro = WhHBAreaPro.reset_index().drop(columns = ['index'])

In [8]:
BarAreaPro.head()

   Unnamed: 0  Zone  Year          Area  Production      Yield
0           4     1  1997    500.000000     1863.00   3.730000
1           5     2  1997  20893.000000   207514.00   9.930000
2           6     3  1997  25691.000000   223088.00   8.680000
3           7     4  1997   2414.881429    24166.85  10.007469
4           8     1  1998    587.580000     5000.41   8.510000

In [9]:
BarCsa = BarCsa.drop([52,53,54,55,56,57,58,59])
MazCsa = MazCsa.drop([52,53,54,55,56,57,58,59])
MilCsa = MilCsa.drop([52,53,54,55,56,57,58,59])
SorgCsa = SorgCsa.drop([52,53,54,55,56,57,58,59])
TefCsa = TefCsa.drop([52,53,54,55,56,57,58,59])
WhetCsa = WhetCsa.drop([52,53,54,55,56,57,58,59])
ChPRCsa = ChPRCsa.drop([52,53,54,55,56,57,58,59])
WhHBCsa = WhHBCsa.drop([52,53,54,55,56,57,58,59])

In [10]:
BarCsa = BarCsa.reset_index().drop(columns = ['index'])
MazCsa = MazCsa.reset_index().drop(columns = ['index'])
MilCsa = MilCsa.reset_index().drop(columns = ['index'])
SorgCsa = SorgCsa.reset_index().drop(columns = ['index'])
TefCsa = TefCsa.reset_index().drop(columns = ['index'])
WhetCsa = WhetCsa.reset_index().drop(columns = ['index'])
ChPRCsa = ChPRCsa.reset_index().drop(columns = ['index'])
WhHBCsa = WhHBCsa.reset_index().drop(columns = ['index'])

In [11]:
WhHBCsa.head()

,Unnamed: 0,Zone,Irrg_Yes,Irrg_No,Seed_Improved,Seed_Not_Improved,Damage_Yes,Damage_No,Dreason_Crop_disease,Dreason_Frost,...,D22a_Urea_NPS,D22a_Mixed,D23_Manure,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight
0,1,1,0.0,72.0,0.0,72.0,22.0,48.0,0.0,0.0,...,0.0,0,13.0,1.0,0,1.0,0.0,0,0.0,10983.27
1,2,2,14.0,1449.0,6.0,1457.0,880.0,582.0,31.0,7.0,...,0.0,0,570.0,81.0,0,177.0,0.0,0,0.0,305751.82
2,3,3,25.0,2474.0,27.0,2472.0,2129.0,370.0,3.0,3.0,...,0.0,0,978.0,255.0,0,156.0,0.0,0,0.0,348274.08
3,5,4,0.0,74.0,0.0,74.0,1.0,73.0,0.0,0.0,...,0.0,0,29.0,10.0,0,4.0,0.0,0,0.0,6040.31
4,1,1,0.0,53.0,0.0,53.0,43.0,10.0,1.0,0.0,...,0.0,0,15.0,0.0,0,0.0,0.0,0,0.0,7806.76

In [12]:
MetroData.head()

,Name,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS
0,Shire Endasilasse,1993,76.983333,27.466667,12.575000,52.592245,1.783333,12.359170
1,Axum Po.St.,1993,57.647542,29.802796,19.996551,45.495155,1.783333,34.862082
2,Adigrat,1993,42.221347,37.327459,14.618125,47.173237,10.400884,13.845825
3,Humera,1993,51.505487,41.522154,31.280487,49.188725,10.645464,18.271932
4,Shire Endasilasse,1994,64.739227,27.389744,12.744231,52.592245,1.729487,12.359170

In [13]:
MetroData = MetroData.drop([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,60,61,62,63])

In [14]:
MetroData = MetroData.reset_index()

In [15]:
MetroData.head()

,index,Name,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS
0,16,Shire Endasilasse,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170
1,17,Axum Po.St.,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082
2,18,Adigrat,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941
3,19,Humera,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932
4,20,Shire Endasilasse,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638

In [16]:
FinBar = pd.DataFrame()
FinMaz = pd.DataFrame()
FinMil = pd.DataFrame()
FinSorg = pd.DataFrame()
FinTef = pd.DataFrame()
FinWhet = pd.DataFrame()
FinChPR = pd.DataFrame()
FinWhHB = pd.DataFrame()

In [17]:
FinBar['Zone']  = BarCsa['Zone']

FinBar[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinBar[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = BarCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinBar[['Area', 'Production', 'Yield']] = BarAreaPro[['Area', 'Production', 'Yield']]
FinBar.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,500.000000,1863.00,3.730000
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,20893.000000,207514.00,9.930000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,25691.000000,223088.00,8.680000
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,2414.881429,24166.85,10.007469
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,587.580000,5000.41,8.510000

In [18]:
FinBar.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,500.000000,1863.00,3.730000
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,20893.000000,207514.00,9.930000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,25691.000000,223088.00,8.680000
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,2414.881429,24166.85,10.007469
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,587.580000,5000.41,8.510000

In [19]:
FinMaz['Zone']  = MazCsa['Zone']

FinMaz[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinMaz[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = MazCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinMaz[['Area', 'Production', 'Yield']] = MazAreaPro[['Area', 'Production', 'Yield']]
FinMaz.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,21084.00,296878.00,14.08
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,18023.00,213105.00,11.82
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,3069.00,25440.00,8.29
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,3128.00,45220.00,14.45
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,2.0,921.0,...,3.0,0.0,35.0,3.0,0.0,14.0,141910.34,17063.93,320066.85,18.76

In [20]:
FinMil['Zone']  = MilCsa['Zone']

FinMil[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinMil[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = MilCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinMil[['Area', 'Production', 'Yield']] = MilAreaPro[['Area', 'Production', 'Yield']]
FinMil.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,33574.00,259319.00,7.72
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,12648.00,69713.00,5.51
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,1699.00,8292.00,4.88
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,7439.00,114152.00,15.34
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,1.0,910.0,...,19.0,1.0,4.0,0.0,0.0,0.0,140341.87,34578.52,389048.93,11.25

In [21]:
FinSorg['Zone']  = SorgCsa['Zone']

FinSorg[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinSorg[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = SorgCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinSorg[['Area', 'Production', 'Yield']] = SorgAreaPro[['Area', 'Production', 'Yield']]
FinSorg.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,48510.00,621019.00,12.80
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,32977.00,255827.00,7.76
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,1218.00,7668.00,6.30
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,25731.00,333488.00,12.96
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,1.0,1067.0,...,15.0,0.0,13.0,0.0,0.0,0.0,168693.45,58735.34,895585.42,15.25

In [22]:
FinTef['Zone']  = TefCsa['Zone']

FinTef[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinTef[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = TefCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinTef[['Area', 'Production', 'Yield']] = TefAreaPro[['Area', 'Production', 'Yield']]
FinTef.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,27309.00,200440.00,7.34
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,44763.00,303461.00,6.78
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,7794.00,58982.00,7.57
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,4814.00,69630.00,14.46
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,1.0,880.0,...,4.0,0.0,4.0,0.0,0.0,0.0,135553.23,31962.65,294254.54,9.21

In [23]:
FinWhet['Zone']  = WhetCsa['Zone']

FinWhet[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinWhet[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = WhetCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinWhet[['Area', 'Production', 'Yield']] = WhetAreaPro[['Area', 'Production', 'Yield']]
FinWhet.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,14.45,156.870000,10.856055
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,18023.00,213105.000000,11.820000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,18329.00,172892.000000,9.430000
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,347.00,26633.146667,76.752584
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1126.46,14.45,156.870000,10.860000

In [24]:
FinChPR['Zone']  = ChPRCsa['Zone']

FinChPR[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinChPR[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = ChPRCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinChPR[['Area', 'Production', 'Yield']] = ChPRAreaPro[['Area', 'Production', 'Yield']]
FinChPR.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0,1.0,0,0.0,0.0,10983.27,3240.0000,18048.000000,5.570000
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0,177.0,0,0.0,0.0,305751.82,1060.0000,7241.000000,6.830000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0,156.0,0,0.0,0.0,348274.08,4781.0000,42179.000000,8.820000
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0,4.0,0,0.0,0.0,6040.31,477.1375,3614.686667,7.575776
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,1.0,101.0,...,4.0,0,0.0,0,0.0,0.0,16455.81,3730.4600,32017.570000,8.580000

In [25]:
FinWhHB['Zone']  = WhHBCsa['Zone']

FinWhHB[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']] = MetroData[['Year', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']]

FinWhHB[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] = WhHBCsa[['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight']] 

FinWhHB[['Area', 'Production', 'Yield']] = WhHBAreaPro[['Area', 'Production', 'Yield']]
FinWhHB.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0,1.0,0.0,0,0.0,10983.27,293.375,2573.395,8.771692
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0,177.0,0.0,0,0.0,305751.82,567.000,3117.000,5.500000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0,156.0,0.0,0,0.0,348274.08,4.260,4446.041,29.270582
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0,4.0,0.0,0,0.0,6040.31,45.000,303.000,6.800000
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,53.0,...,0.0,0,0.0,0.0,0,0.0,7806.76,561.820,2896.110,5.150000

In [26]:
for var in['Irrg_Yes', 'Irrg_No', 'Seed_Improved', 'Seed_Not_Improved', 'Damage_Yes', 'Damage_No', 'Dreason_Crop_disease', 'Dreason_Frost', 'Dreason_Floods', 'Dreason_Locust', 'Dreason_Insects',
       'Dreason_Toolittle_rain', 'Dreason_Toomuch_rain', 'Dreason_Wild_animals', 'Dreason_Birds', 'Dreason_Hail',
       'Dreason_Weeds', 'Dreason_ShortageSeed', 'Dreason_DepletionSoil', 'Dreason_Security', 'Dreason_UseBadCrop', 'Dmeasure_Yes', 'Dmeasure_No',
       'Dmtype_Chemical', 'Dmtype_NonChemical', 'Dmtype_Both', 'Dmchem_Insecticide', 'Dmchem_Herbicide', 'Dmchem_Fungicide',
       'Dmchem_Insectcide_Her', 'Dmchem_Insectcide_Fun', 'Dmchem_Herbicide_Fung', 'Dmchem_All', 'Fert_Yes', 'Fert_No',
       'Ferttype_Natural', 'Ferttype_Chemical', 'Ferttype_Both', 'D22a_Urea', 'D22a_DAP', 'D22a_Urea_DAP', 'D22a_NPS', 'D22a_Urea_NPS', 'D22a_Mixed',
       'D23_Manure', 'D23_Compost', 'D23_Organic', 'D23_Manure_Compost', 'D23_Manure_Organic', 'D23_Compost_Organic', 'D23_All', 'Fweight','Area', 'Production', 'Yield', 'PRECIP', 'TMPMAX','TMPMIN', 'RELHUM', 'WINDLY', 'SUNHRS']:
    
    FinBar[var] = FinBar[var].fillna(FinBar[var].mean())
    FinMaz[var] = FinMaz[var].fillna(FinMaz[var].mean())
    FinMil[var] = FinMil[var].fillna(FinMil[var].mean())
    FinSorg[var] = FinSorg[var].fillna(FinSorg[var].mean())
    FinTef[var] = FinTef[var].fillna(FinTef[var].mean())
    FinWhet[var] = FinWhet[var].fillna(FinWhet[var].mean())
    FinChPR[var] = FinChPR[var].fillna(FinChPR[var].mean())
    FinWhHB[var] = FinWhHB[var].fillna(FinWhHB[var].mean())

In [27]:
FinWhHB.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0,1.0,0.0,0,0.0,10983.27,293.375,2573.395,8.771692
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0,177.0,0.0,0,0.0,305751.82,567.000,3117.000,5.500000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0,156.0,0.0,0,0.0,348274.08,4.260,4446.041,29.270582
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0,4.0,0.0,0,0.0,6040.31,45.000,303.000,6.800000
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,53.0,...,0.0,0,0.0,0.0,0,0.0,7806.76,561.820,2896.110,5.150000

In [28]:
# make a list of the variables that contain missing values
vars_with_na = [var for var in FinBar.columns if FinBar[var].isnull().sum()>1]

# print the variable name and the percentage of missing values
for var in vars_with_na:
    print(var, np.round(FinBar[var].isnull().mean(), 3),  ' % missing values')

In [29]:
# make a list of the variables that contain missing values
vars_with_na = [var for var in FinMaz.columns if FinMaz[var].isnull().sum()>1]

# print the variable name and the percentage of missing values
for var in vars_with_na:
    print(var, np.round(FinMaz[var].isnull().mean(), 3),  ' % missing values')

In [30]:
# make a list of the variables that contain missing values
vars_with_na = [var for var in FinMil.columns if FinMil[var].isnull().sum()>1]

# print the variable name and the percentage of missing values
for var in vars_with_na:
    print(var, np.round(FinMil[var].isnull().mean(), 3),  ' % missing values')

In [31]:
# make a list of the variables that contain missing values
vars_with_na = [var for var in FinSorg.columns if FinSorg[var].isnull().sum()>1]

# print the variable name and the percentage of missing values
for var in vars_with_na:
    print(var, np.round(FinSorg[var].isnull().mean(), 3),  ' % missing values')

In [32]:
# make a list of the variables that contain missing values
vars_with_na = [var for var in FinWhet.columns if FinWhet[var].isnull().sum()>1]

# print the variable name and the percentage of missing values
for var in vars_with_na:
    print(var, np.round(FinWhet[var].isnull().mean(), 3),  ' % missing values')

In [33]:
FinBar.to_csv('C:/Users/hp/FIN_DATA/FinBar.csv')
FinMaz.to_csv('C:/Users/hp/FIN_DATA/FinMaz.csv')
FinMil.to_csv('C:/Users/hp/FIN_DATA/FinMil.csv')
FinSorg.to_csv('C:/Users/hp/FIN_DATA/FinSorg.csv')
FinTef.to_csv('C:/Users/hp/FIN_DATA/FinTef.csv')
FinWhet.to_csv('C:/Users/hp/FIN_DATA/FinWhe.csv')
FinChPR.to_csv('C:/Users/hp/FIN_DATA/FinChPR.csv')
FinWhHB.to_csv('C:/Users/hp/FIN_DATA/FinWhHB.csv')

In [34]:
FinRes = pd.DataFrame()

In [35]:
FinRes = FinBar
FinRes = FinRes.append(FinMaz)
FinRes = FinRes.append(FinMil)
FinRes = FinRes.append(FinSorg)
FinRes = FinRes.append(FinTef)
FinRes = FinRes.append(FinWhet)
FinRes = FinRes.append(FinChPR)
FinRes = FinRes.append(FinWhHB)

In [36]:
FinRes.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Compost,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,500.000000,1863.00,3.730000
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,81.0,0.0,177.0,0.0,0.0,0.0,305751.82,20893.000000,207514.00,9.930000
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,255.0,0.0,156.0,0.0,0.0,0.0,348274.08,25691.000000,223088.00,8.680000
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,10.0,0.0,4.0,0.0,0.0,0.0,6040.31,2414.881429,24166.85,10.007469
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,72.0,...,1.0,0.0,1.0,0.0,0.0,0.0,10983.27,587.580000,5000.41,8.510000

In [37]:
FinRes['Crop'] = [ 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
             2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
             3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
             4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
             5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
             6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
             7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
             8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8]

In [38]:
FinRes.head()

,Zone,Year,PRECIP,TMPMAX,TMPMIN,RELHUM,WINDLY,SUNHRS,Irrg_Yes,Irrg_No,...,D23_Organic,D23_Manure_Compost,D23_Manure_Organic,D23_Compost_Organic,D23_All,Fweight,Area,Production,Yield,Crop
0,1,1997,69.269978,29.656865,14.336538,52.592245,1.698718,12.359170,0.0,72.0,...,0.0,1.0,0.0,0.0,0.0,10983.27,500.000000,1863.00,3.730000,1
1,2,1997,57.647542,29.802796,19.996551,45.495155,1.698718,34.862082,14.0,1449.0,...,0.0,177.0,0.0,0.0,0.0,305751.82,20893.000000,207514.00,9.930000,1
2,3,1997,34.947796,24.863651,9.024471,57.551787,7.858578,12.400941,25.0,2474.0,...,0.0,156.0,0.0,0.0,0.0,348274.08,25691.000000,223088.00,8.680000,1
3,4,1997,60.206309,38.878724,26.824670,47.743268,10.645464,18.271932,0.0,74.0,...,0.0,4.0,0.0,0.0,0.0,6040.31,2414.881429,24166.85,10.007469,1
4,1,1998,78.737179,27.805128,18.107981,52.592245,1.575641,11.397638,0.0,72.0,...,0.0,1.0,0.0,0.0,0.0,10983.27,587.580000,5000.41,8.510000,1

In [39]:
FinRes.to_csv('C:/Users/hp/FIN_DATA/Final_Data_Draft.csv')